;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Blueprints/UI/Data/DTG_Info.DTG_Info
+GameplayTagTableList=/Game/Blueprints/AbilitySystem/GameplayTags/DTG_PrimaryAttributes.DTG_PrimaryAttributes
+GameplayTagTableList=/Game/Blueprints/AbilitySystem/GameplayTags/DTG_VitalAttributes.DTG_VitalAttributes
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16

